export const DATABASE_TYPE = "postgres";

export enum PROVIDERS {
	BALANCE_PROVIDERS = "BALANCE_REPOSITORY",
	USER_PROVIDERS = "USERS_REPOSITORY",
	MOVEMENT_PROVIDERS = "MOVEMENTS_REPOSITORY",
	ORM_PROVIDER = "DATA_SOURCE",
}

export enum TYPE_ORM_TYPES {
	VARCHAR = "varchar",
	NUMERIC = "numeric",
	INT = "int",
	TIMESTAMP = "timestamp",
}

export const CURRENT_TIMESTAMP = "CURRENT_TIMESTAMP";