export const DATABASE_TYPE = "cockroachdb";

export enum PROVIDERS {
	BALANCE_PROVIDERS = "BALANCE_REPOSITORY",
	USER_PROVIDERS = "USERS_REPOSITORY",
	MOVEMENT_PROVIDERS = "MOVEMENTS_REPOSITORY",
	ORM_PROVIDER = "DATA_SOURCE",
}

export enum TYPE_ORM_TYPES {
	TEXT = "text",
	DOUBLE = "double",
	INT = "int"
}

export enum TYPE_ORM_PROPERTIES_LENGTHS {
	NAME_LENGTH = 50,
	PASSWORD_LENGTH = 40,
	EMAIL_LENGTH = 80,
	CONCEPT_LENGTH = 60,
	TYPE_LENGTH = 40
}